# Model configuration
MODEL_ID: "mistralai/Mistral-7B-Instruct-v0.2" # The model ID to use for inference
ENDPOINT_NAME: "mistralai/Mistral-7B-Instruct-v0.2" # The endpoint name for the model

# Inference settings
INFERENCE_ENDPOINTS_URL: "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2" # The URL for the inference endpoint
MAX_NEW_TOKENS: 1024 # Maximum number of new tokens to generate

# Dataset configuration
INPUT_DATASET_HUB_ID: "davanstrien/aya_dataset_dutch" # The input dataset ID on Hugging Face Hub
OUTPUT_DATASET_HUB_ID: "davanstrien/aya_dpo" # The output dataset ID on Hugging Face Hub
SPLIT: "test" # The dataset split to use (e.g., train, validation, test)

# Processing settings
INPUT_BATCH_SIZE: 10 # The batch size for processing input data

# External service integration
ARGILLA_SPACE_URL: "https://davanstrien-argilla.hf.space" # The URL for the Argilla space
