name: Update Progress Data

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/actions/update-progress/requirements.txt

      - name: Run update script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          ARGILLA_API_KEY: ${{ secrets.ARGILLA_API_KEY }}
        run: |
          python .github/actions/update-progress/src/dashboard.py
